stages:
  load_data:
    cmd: python src/load_data.py --config_path=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - wine_quality.csv
    outs:
    - data/raw/winequality.csv
  split_data:
    cmd: python src/split_data.py --config_path=params.yaml
    deps:
    - data/raw/winequality.csv
    - src/split_data.py
    outs:
    - data/processed/test_winequality.csv
    - data/processed/train_winequality.csv
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config_path=params.yaml
    deps:
    - data/processed/test_winequality.csv
    - data/processed/train_winequality.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    outs:
    - models/model.joblib
